# -*- coding: utf-8 -*-
# pylint: disable=R0903
#       R0903: Too few public methods

"""
This module is the SQLAlchemy_ ORM for the ``redacted`` database.

It was auto-generated by running ``flask-sqlacodegen $conn_str --noviews
--outfile redacted.py`` and then modified to:

1. remove non-declarative tables
2. add relationships
3. Add class docstrings
4. Fix tables names to not have spaces and to be CamelCase.

Created by Douglas Thor on 2016-08-08 23:15:29 UTC.

.. _SQLAlchemy: http://www.sqlalchemy.org/
"""
# ---------------------------------------------------------------------------
### Imports
# ---------------------------------------------------------------------------
# Standard Library

# Third-Party
from sqlalchemy import Boolean
from sqlalchemy import Column
from sqlalchemy import Date
from sqlalchemy import DateTime
from sqlalchemy import Float
from sqlalchemy import ForeignKey
from sqlalchemy import Index
from sqlalchemy import Integer
from sqlalchemy import String
from sqlalchemy import Time
from sqlalchemy import UniqueConstraint
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.schema import FetchedValue

# Package / Application
from . import module_u


# ---------------------------------------------------------------------------
### Constants
# ---------------------------------------------------------------------------
Base = declarative_base()
metadata = Base.metadata
